# Generated by Django 2.2.6 on 2021-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('origin', models.CharField(max_length=128, verbose_name='来源')),
                ('remark', models.CharField(max_length=128, verbose_name='备注')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
                'db_table': 'stock',
                'ordering': ['-name'],
            },
        ),
    ]
