# Generated by Django 2.2.6 on 2021-06-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210603_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=128, unique=True, verbose_name='线程id')),
                ('status', models.IntegerField(unique=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '采集器状态',
                'verbose_name_plural': '采集器状态',
                'db_table': 'CollectorStatus',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(max_length=128, verbose_name='股票名称')),
                ('startprice', models.CharField(max_length=128, verbose_name='今开')),
                ('yprice', models.CharField(max_length=128, verbose_name='昨收')),
                ('nprice', models.CharField(max_length=128, verbose_name='当前价格')),
                ('hprice', models.CharField(max_length=128, verbose_name='最高价')),
                ('lprice', models.CharField(max_length=128, verbose_name='最低价')),
                ('bidingprice', models.CharField(max_length=128, verbose_name='竞买价')),
                ('auctionprice', models.CharField(max_length=128, verbose_name='竞卖价')),
                ('tradingvolume', models.CharField(max_length=128, verbose_name='成交量')),
                ('tradingamount', models.CharField(max_length=128, verbose_name='成交金额')),
                ('buy1', models.CharField(max_length=128, verbose_name='买一量')),
                ('buy1price1', models.CharField(max_length=128, verbose_name='买一')),
                ('buy2', models.CharField(max_length=128, verbose_name='买二量')),
                ('buy2price', models.CharField(max_length=128, verbose_name='买二')),
                ('buy3', models.CharField(max_length=128, verbose_name='买三量')),
                ('buy3price', models.CharField(max_length=128, verbose_name='买三')),
                ('buy4', models.CharField(max_length=128, verbose_name='买四量')),
                ('buy4price', models.CharField(max_length=128, verbose_name='买四')),
                ('buy5', models.CharField(max_length=128, verbose_name='买五量')),
                ('buy5price', models.CharField(max_length=128, verbose_name='买五')),
                ('sale1', models.CharField(max_length=128, verbose_name='卖一量')),
                ('sale1price', models.CharField(max_length=128, verbose_name='卖一')),
                ('sale2', models.CharField(max_length=128, verbose_name='卖二量')),
                ('sale2price', models.CharField(max_length=128, verbose_name='卖二')),
                ('sale3', models.CharField(max_length=128, verbose_name='卖三量')),
                ('sale3price', models.CharField(max_length=128, verbose_name='卖三')),
                ('sale4', models.CharField(max_length=128, verbose_name='卖四量')),
                ('sale4price', models.CharField(max_length=128, verbose_name='卖四')),
                ('sale5', models.CharField(max_length=128, verbose_name='卖五量')),
                ('sale5price', models.CharField(max_length=128, verbose_name='卖五')),
                ('date', models.CharField(max_length=128, unique=True, verbose_name='日期')),
                ('time', models.CharField(max_length=128, unique=True, verbose_name='时间')),
                ('status', models.CharField(max_length=128, verbose_name='状态')),
            ],
            options={
                'verbose_name': '分时量价',
                'verbose_name_plural': '分时量价',
                'db_table': 'stockprice',
                'ordering': ['time'],
            },
        ),
    ]
