# Generated by Django 2.2.6 on 2021-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_collectorstatus_stockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LbHsl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='股票代码')),
                ('date', models.DateField(max_length=128, unique=True, verbose_name='日期')),
                ('startprice', models.CharField(max_length=128, unique=True, verbose_name='开盘价')),
                ('hprice', models.CharField(max_length=128, unique=True, verbose_name='最高价')),
                ('eprice', models.CharField(max_length=128, unique=True, verbose_name='收盘价')),
                ('lprice', models.CharField(max_length=128, unique=True, verbose_name='最低价')),
                ('volume', models.CharField(max_length=128, unique=True, verbose_name='成交量')),
                ('rfprice', models.CharField(max_length=128, unique=True, verbose_name='涨跌额')),
                ('applies', models.CharField(max_length=128, unique=True, verbose_name='涨跌幅')),
                ('daily5price', models.CharField(max_length=128, unique=True, verbose_name='5日均价')),
                ('daily10price', models.CharField(max_length=128, unique=True, verbose_name='10日均价')),
                ('daily20price', models.CharField(max_length=128, unique=True, verbose_name='20日均价')),
                ('daily5volume', models.CharField(max_length=128, unique=True, verbose_name='5日均量')),
                ('daily10volume', models.CharField(max_length=128, unique=True, verbose_name='10日均量')),
                ('daily20volume', models.CharField(max_length=128, unique=True, verbose_name='20日均量')),
                ('turnoverrate', models.CharField(max_length=128, unique=True, verbose_name='换手率')),
            ],
            options={
                'verbose_name': '量比换手率',
                'verbose_name_plural': '量比换手率',
                'db_table': 'lb_hsl_stock',
            },
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(max_length=128, unique=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='time',
            field=models.TimeField(max_length=128, unique=True, verbose_name='时间'),
        ),
    ]
